In [3]:
import numpy as np
import pandas as pd

In [4]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [5]:
df=pd.read_csv('gurgaon_properties.csv')

In [6]:
df.shape

(3974, 20)

In [7]:
df.duplicated().sum()

np.int64(13)

In [8]:
df[df.duplicated()]

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
651,4 Bedroom House for sale in Sector 48 Gurgaon,house,vipul tatvam villa,8.40,21000.0,4000.0,Plot area 4000(371.61 sq.m.),4,5,3+,"pooja room,study room,servant room","Sector 48 Gurgaon, Gurgaon, Haryana",2.0,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1044,4 Bedroom House for sale in Sector 55 Gurgaon,house,NaN,3.55,24500.0,1449.0,Plot area 161(134.62 sq.m.),4,4,3+,not available,"Sector 55 Gurgaon, Gurgaon, Haryana",2.0,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",For sale 161yd independent house sector 55 gur...,"['6 Wardrobe', '9 Fan', '6 Geyser', '17 Light'...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1715,3 Bedroom House for sale in Sector 48 Gurgaon,house,vipul tatvam villa,7.25,27971.0,2592.0,Plot area 288(240.8 sq.m.),3,4,2,"servant room,study room,store room,pooja room","A111, Sector 48 Gurgaon, Gurgaon, Haryana",2.0,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Sector 48 gurgaon is one of gurgaon's most sou...,"['4 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1788,4 Bedroom House for sale in Sector 112 Gurgaon,house,experion windchants,7.99,12519.0,6382.0,Built Up area: 6382 (592.91 sq.m.),4,6,3,"servant room,store room,pooja room","Wp1- Wp-8, Sector 112 Gurgaon, Gurgaon, Haryana",2.0,South-East,0 to 1 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale 4bhk + servant luxury villa...,"['1 Exhaust Fan', '7 Geyser', '1 Stove', '10 A...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3043,12 Bedroom House for sale in DLF Phase 1,house,luxury dlf city floors,8.25,45833.0,1800.0,Plot area 200(167.23 sq.m.),12,12,3+,servant room,"A Block Dlf-1, DLF Phase 1, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",For sale brand new building having stilt and 4...,"['20 Fan', '1 Exhaust Fan', '12 Geyser', '40 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3143,4 Bedroom House for sale in Sector 91 Gurgaon,house,dlf new town heights,2.50,7058.0,3542.0,Plot area 3400(315.87 sq.m.),4,4,3+,"pooja room,study room,servant room,store room","Sector 91 Gurgaon, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['MG Road Metro Station', 'RHM Public School',...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '9 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3174,6 Bedroom House for sale in Uppals Southend,house,uppal southend,3.75,25562.0,1467.0,Plot area 163(136.29 sq.m.),6,6,3,others,"Uppals Southend, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address...Uppal southend sector 49 w blook \n6...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3278,8 Bedroom House for sale in Palam Vihar,house,NaN,5.60,17284.0,3240.0,Plot area 360(301.01 sq.m.),8,6,3+,"pooja room,study room,servant room,store room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
3326,4 Bedroom House for sale in C Block Sushant Lo...,house,NaN,5.75,29716.0,1935.0,Plot area 215(179.77 sq.m.),4,4,2,"servant room,pooja room,store room","C Block Sushant Lok Phase 1, Gurgaon, Haryana",2.0,North,10+ Year Old,"['Sector 42-43 metro station', 'Huda city cent...",North facing property\n100 meter from vaipar k...,NaN,"['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3372,4 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.40,20690.0,2610.0,Plot area 290(242.48 sq.m.),4,5,3+,"pooja room,store room,study room,servant room","290 Sqyd Duplex Villa, Sector 70A Gurgaon, Gur...",3.0,North,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","Bptp duplex villa 290 sqyd plot size, private ...","['5 Wardrobe', '1 Water Purifier', '6 Geyser',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3553,4 Bedroom House for sale in Sector 86 Gurgaon,house,dlf new town heights,2.50,7058.0,3542.0,Plot area 3400(315.87 sq.m.),4,4,3+,"study room,servant room,pooja room,store room","Sector 86 Gurgaon, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '12 Fan', '1 Exhaust F...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3565,3 Bedroom House for sale in Palam Vihar,house,NaN,2.55,16378.0,1557.0,Plot area 173(144.65 sq.m.),3,3,2,not available,"Palam Vihar, Gurgaon, Haryana",2.0,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",173 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...",['Park'],"['Environment5 out of 5', 'Lifestyle5 out of 5..."
3615,5 Bedroom House for sale in Greenwood City,house,NaN,17.00,37777.0,4500.0,Plot area 4500(418.06 sq.m.),5,8,3+,"pooja room,study room,servant room,store room","0000, Greenwood City, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ultra luxury kothi for sale in greenwood city ...,"['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4.5 out of 5', 'Lifestyle4 out of..."

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(3961, 20)

In [11]:
df.columns

Index(['property_name', 'property_type', 'society', 'price', 'price_per_sqft',
       'area', 'areaWithType', 'bedRoom', 'bathroom', 'balcony',
       'additionalRoom', 'address', 'floorNum', 'facing', 'agePossession',
       'nearbyLocations', 'description', 'furnishDetails', 'features',
       'rating'],
      dtype='object')

In [12]:
df.isnull().sum()

property_name         0
property_type         0
society             570
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [13]:
#adding sector column
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [14]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,9 Bedroom House for sale in South City 1,house,NaN,South City 1,7.25,29293.0,2475.0,Plot area 275(229.94 sq.m.),9,8,3,servant room,"M-Block, South City 1, Gurgaon, Haryana",4.0,South-West,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...","275yds built-Up building having basement, grou...","['5 Fan', '1 Exhaust Fan', '8 Geyser', '12 Lig...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector 81 Gurgaon,flat,vipul lavanya,Sector 81,1.28,7174.0,1784.0,Carpet area: 1784 (165.74 sq.m.),3,3,3,"pooja room,servant room","T4, 101, Sector 81 Gurgaon, Gurgaon, Haryana",1.0,North-East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","First floor. Well maintained club house, swimm...","['1 Bed', '3 Wardrobe', '7 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,Sector 107,1.40,5929.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,N,not available,"A02/101 2361sq Ft, Sector 107 Gurgaon, Gurgaon...",1.0,East,0 to 1 Year Old,NaN,Looking for a good 3 bhk apartment in sector 1...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Safety1 out of 5', 'Lifestyle2 out of 5', 'E..."
3,2 BHK Flat in Sector 37C Gurgaon,flat,ild greens,Sector 37C,0.78,5714.0,1365.0,Super Built up area 1365(126.81 sq.m.)Built Up...,2,2,3,not available,"101, Tower-7, Sector 37C Gurgaon, Gurgaon, Har...",1.0,North,5 to 10 Year Old,"['The Esplanade Mall', 'Gurgaon Road', 'Delhi ...","Rooms are well ventilated and airy, good open ...","['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Amenities4.5 out of ..."
4,2 BHK Flat in Sohna,flat,ashiana mulberry,Sohna,1.05,5412.0,1940.0,Super Built up area 1940(180.23 sq.m.)Built Up...,2,2,3,study room,"B109, Sohna, Gurgaon, Haryana",1.0,North,0 to 1 Year Old,"['Discount Department Store', 'Badshahpur Sohn...",This lovely 2 bhk apartment/flat in sohna is a...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [15]:
df['sector']=df['sector'].str.lower()

In [16]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 70                                                     53
sector 37c                                                    53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
laxman vihar                                                  27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 14                                                     15
sector 52                                                     14
sector 3                                                      14
rajendra park                                                 14
dlf phase 5                                                   14
gwal pahari                                                   14
sector 76                                                     14
sector 1 imt manesar                                          14
sector 53                                                     14
laxman vihar phase 2                                          13
sector 36a                                                    13
sector 46                                                     13
sector 38                                                     12
sector 50                                                     12
uppals southend                                               12
sector 93                                                     12
sector 31                                                     12
sohna road                                                    12
sector 39                                                     12
sector 9a                                                     11
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 55                                                      9
sector 95a                                                     9
ashok vihar phase 2                                            9
sector 4                                                       9
south city 1                                                   9
dwarka expressway                                              8
palam vihar extension                                          8
sector 43                                                      8
sector 10a                                                     8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
malibu town                                                    8
sector 89 a                                                    8
sector 59                                                      8
sector 40                                                      8
sector 57                                                      8
sector 51                                                      7
sector 58                                                      7
sector 11                                                      7
surat nagar 1                                                  7
new colony                                                     7
sector 36 sohna                                                7
mianwali colony                                                7
sector 26                                                      7
sector 1                                                       6
rajiv nagar                                                    6
jacobpura                                                      6
ashok vihar                                                    6
jyoti park                                                     6
sector 5                                                       6
new palam vihar                                                5
sector 9                                                       5
chakkarpur                                                     5
sector 30                                                      5
sector 28                                                      5
dayanand colony                                                5
ansal plaza                                                    5
greenwood city                                                 5
subhash nagar                                                  5
arjun nagar                                                    5
sector 105                                                     5
sector 2                                                       5
sector 23a                                                     5
sector 80                                                      5
sushant lok phase 2                                            5
saraswati vihar                                                5
manesar                                                        5
suncity                                                        4
madanpuri                                                      4
sector 12                                                      4
sector 12a                                                     4
devilal colony                                                 4
vishnu garden                                                  4
sector 36                                                      4
surya vihar                                                    4
ravi nagar                                                     4
dharam colony                                                  4
sector 45                                                      4
bhim nagar                                                     4
sector 6                                                       4
sector 3a                                                      4
bhondsi                                                        4
imt manesar                                                    4
shivpuri                                                       4
adarsh nagar                                                   4
garhi harsaru                                                  4
valley view estate                                             4
baldev nagar                                                   4
new                                                            4
sector 17                                                      4
shivaji nagar                                                  4
krishna colony                                                 4
laxmi garden                                                   3
b block sushant lok phase 1                                    3
sector 73                                                      3
sector 15                                                      3
mg road                                                        3
sector 110 a                                                   3
sector 17a                                                     3
gandhi nagar                                                   3
prem nagar                                                     3
shakti nagar                                                   3
sector 23                                                      3
a block sushant lok phase 1                                    3
sector 88b                                                     3
sector 8                                                       3
patel nagar                                                    3
sector 17b                                                     3
sector 27                                                      3
maruti kunj                                                    3
rajiv chowk                                                    2
hira nagar                                                     2
manohar nagar                                                  2
iffco chowk                                                    2
mayfield garden                                                2
shankar vihar                                                  2
sector-11 sohna                                                2
faridabad road                                                 2
west rajiv nagar                                               2
sohna  road                                                    2
sushant lok                                                    2
block a surya vihar                                            2
sector 15 part 2                                               2
golf course road                                               2
farukhnagar                                                    2
surat nagar phase 2                                            2
bhawani enclave                                                2
acharya puri                                                   2
nars                                                           2
new basti                                                      2
golf course ext road                                           2
sector 21                                                      2
, delhi ncr                                                    2
pratap nagar                                                   2
sector 24                                                      2
sector 15 part 1                                               2
sector 32                                                      2
lajpat nagar                                                   2
sheetla colony                                                 2
shanti nagar                                                   2
new palam vihar phase 1                                        2
sector-2 sohna                                                 2
sector 41                                                      2
rosewood                                                       2
sispal vihar                                                   2
mohan nagar                                                    2
ambience island                                                2
daulatabad                                                     2
new palam vihar phase 2                                        2
surat nagar                                                    2
samaspur                                                       2
bissar                                                         2
mahavir pura                                                   1
g block dlf city phase 1                                       1
block g sector-57                                              1
sadar bazar                                                    1
damdma                                                         1
sector-7 hous                                                  1
sector 9b                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
south city                                                     1
sector 4 urban estate                                          1
om nagar                                                       1
nirvana country pocket h                                       1
rattan garden                                                  1
block h ashok vihar phase iii extension                        1
civil l                                                        1
sector-5 sohna                                                 1
kanahi                                                         1
near khandsa road                                              1
alipur                                                         1
khandsa                                                        1
begampur khatola                                               1
pataudi road                                                   1
bhimgarh kheri phase 3                                         1
sector 37b                                                     1
sector-35 sohna                                                1
vir nagar                                                      1
new colony, sector 7                                           1
heritage city                                                  1
ashok vihar phase 3                                            1
near pataudi chowk                                             1
jacobpura near sadar bazar                                     1
sector 42                                                      1
sultanpur                                                      1
old delhi road, opp sector-14                                  1
new jyoti park                                                 1
jat colony,fazilpur/taj nagar road                             1
b1 block sector 57                                             1
sector-5 sheetla colony                                        1
mahalaxmi garden, rajendra place                               1
hsiidc plot sector 1 imt manesar                               1
shivji park colony                                             1
laxman vihar, railway road,                                    1
laxmna vihar, phase 2                                          1
carterpuri village                                             1
ashok vihar phase i                                            1
urban estate, sector 5                                         1
lucknow                                                        1
sec 3 bhim vihar part 1 bhimgher kheri                         1
ram nagar                                                      1
ansal's palam vihar                                            1
tekchand nagar                                                 1
sector 17c                                                     1
godrej aria , sector 79 ,                                      1
gopal nagar, garhi ghasita, sonipat                            1
rajiv colony                                                   1
naharpur rupa                                                  1
ats marigold                                                   1
anand garden, sector-105                                       1
saraswati enclave                                              1
bptp                                                           1
near euro                                                      1
saroop garden rajendra park                                    1
kheri                                                          1
sector 21a faridabad                                           1
udyog vihar phase 1                                            1
bhora kalan                                                    1
park view                                                      1
part 3 sector 5                                                1
hno 13 sagar enclave sura                                      1
sector 37a                                                     1
sai kunj                                                       1
huda saraswati vihar                                           1
v block dlf phase 3                                            1
sector 13                                                      1
near nand hospital                                             1
ravi nager basai road                                          1
cyber city                                                     1
dhankot                                                        1
sector 5 chowk                                                 1
near sector 1 market                                           1
garauli kalan                                                  1
Name: count, dtype: int64

In [17]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')



df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('vishal vihar','sector 11')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')


df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [18]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [19]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [20]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('ashok vihar phase 1','sector 5')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3','sector 5')


df['sector'] = df['sector'].str.replace('gwal pahari','sector 2')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12a')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('sushant lok phase 5','sector 55')
df['sector'] = df['sector'].str.replace('mehrauli road','sector 28')

In [21]:
a=df['sector'].value_counts()[df['sector'].value_counts()>3]

In [22]:
a.index

Index(['sohna road', 'sector 102', 'sector 85', 'sector 92', 'sector 69',
       'sector 90', 'sector 65', 'sector 81', 'sector 109', 'sector 79',
       ...
       'sector 5', 'sector 21', 'sector 1', 'sector 80', 'sector 23a',
       'sector 30', 'new sector 2', 'new', 'sector 3a', 'sector 36'],
      dtype='object', name='sector', length=120)

In [23]:
df=df[df['sector'].isin(a.index)]

In [24]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

/tmp/ipython-input-24-3954173571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
/tmp/ipython-input-24-3954173571.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
/tmp/ipython-input-24-3954173571.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
/tmp/ipython-input-24-3954173571.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
/tmp/ipython-input-24-3954173571.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
/tmp/ipython-input-24-3954173571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
/tmp/ipython-input-24-3954173571.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
/tmp/ipython-input-24-3954173571.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
/tmp/ipython-input-24-3954173571.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [25]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

/tmp/ipython-input-25-600812590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
/tmp/ipython-input-25-600812590.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
/tmp/ipython-input-25-600812590.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
/tmp/ipython-input-25-600812590.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
/tmp/ipython-input-25-600812590.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
/tmp/ipython-input-25-600812590.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
/tmp/ipython-input-25-600812590.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
/tmp/ipython-input-25-600812590.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [26]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
184,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,2027-06-01 00:00:00,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
560,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1178,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3047,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [27]:
df.loc[1570,'sector']='sector 76'
df.loc[2210,'sector']='sector 92'
df.loc[3043,'sector']='sector 90'
df.loc[3855,'sector']='sector 37'

In [28]:
df[df['sector']=='new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
32,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2.0,2.0,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1326,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2.0,2.0,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1728,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2.0,1.0,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
1838,3 Bedroom House for sale in New Palam Vihar,house,NaN,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3513,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2.0,2.0,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [29]:
df.loc[[189,419,530,2993,3860],'sector']='sector 110'

In [30]:
df.shape

(3771, 21)

In [31]:
df.drop(columns=['property_name','address','description','rating'],inplace=True)

In [32]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1718,flat,smart world gems,sector 89,1.71,12000.0,1425.0,Built Up area: 1423 (132.2 sq.m.),3.0,2.0,N,not available,3.0,NaN,undefined,"['Sant Soordas Sihi Metro Station', 'Airia Mal...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
384,flat,bestech park view grand spa,sector 81,2.30,8646.0,2660.0,Super Built up area 2660(247.12 sq.m.)Built Up...,3.0,4.0,3,servant room,7.0,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, IMT Manesar', 'Dwa...","['3 Wardrobe', '1 Stove', '1 Modular Kitchen',...","['Feng Shui / Vaastu Compliant', 'Security / F..."
47,flat,alpha corp gurgaonone,sector 84,2.20,7586.0,2900.0,Carpet area: 2900 (269.42 sq.m.),4.0,4.0,3,servant room,10.0,South,1 to 5 Year Old,"['Delhi Public School', 'Raheja Market', 'Sapp...",NaN,"['Lift(s)', 'Maintenance Staff', 'Park', 'Visi..."
112,flat,m3m golf hills,sector 79,1.45,10211.0,1420.0,Carpet area: 1420 (131.92 sq.m.),2.0,2.0,3,not available,15.0,NaN,2027-07-01 00:00:00,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",[],NaN
1490,flat,dlf the skycourt,sector 86,2.20,11500.0,1913.0,Super Built up area 1930(179.3 sq.m.),3.0,3.0,1,pooja room,7.0,NaN,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...","['1 Water Purifier', '1 Fridge', '1 Exhaust Fa...","['Private Garden / Terrace', 'Intercom Facilit..."

In [33]:
#feature engineering
#on ----> areawithType,additionalRoom,facing,agePossession,furnishDetails,features

In [34]:
df.to_csv('gurgaon_properties_v2.csv',index=False)